import numpy as np  # type: ignore[import]
a=[1,2,3,4]
b=[5,6,7,8]
array=np.array([a,b])
print(array)
print(array.shape)
print(array.ndim)
# ar=array.flatten()
# print(ar)
# print(array[:3])
ar=np.array([1,2,3,4,5,6,7,8])
print(ar)
print(ar[:5])
print(ar.dtype)
zero=np.zeros((3,4))
print("zero:", zero)
one=np.ones((3,4))
print("one:", one)
empty=np.empty((3,4))
print("empty:", empty)
range=np.arange(9)
print("range:", range)
steprange=np.arange(1,10,2)
print("steprange:", steprange)
identity=np.eye(5)
print("identity:", identity)
fullmtx=np.full((2,4),7)
print("fullmtx:", fullmtx)
linspace=np.linspace(1,10,5,dtype=np.int32)
print("linspace:", linspace)
print("linspace dtype:", linspace.dtype)

zero=zero+np.ones((3,4))
print("zero after addition:", zero)
print("zero shape:", zero.shape)
print("zero ndim:", zero.ndim)
print("zero size:", zero.size)
threedarray=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("3darray:", threedarray)
print("3darray shape:", threedarray.shape)
print("3darray ndim:", threedarray.ndim)
a=np.array([1,2,3])
print(a+10)
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[10],[20]])
print(b+c)