import pandas as pd
data=pd.read_csv("./Pandas_Day_4_Real_World_Sales_Data.csv")
print(data)
print(data.dtypes)
print(data["Order_Date"].dtype)
print(data["Price"].dtype)
print(data["Order_Date"].map(type).value_counts())
data["Order_Date"]=data["Order_Date"].astype("datetime64[ns]")
print(data["Order_Date"].dtype)
print(data['Order_Date'])
values=pd.Series(["100","200","hello"])
print(values.dtype)
print(values)
# values=values.astype("int32")
values=pd.to_numeric(values,errors="coerce")
print(values)
data["reveunue"]=data["Price"]*data["Quantity"]
print(data["reveunue"])
print(f"high cost products : {data[data["Price"]>60000]}")